[package]
name = "rust_i_telex_teilnehmerserver"
version = "0.1.0"
authors = ["soruh <mail@soruh.de>"]
edition = "2018"

[dependencies]
nom = "4.2.3"
byteorder = "1.3.2" # should be obsolete
dotenv = "0.9.0"
crossbeam = "0.7.2"
sqlite = "0.25.0"


#[dependencies.diesel]
#version = "1.0.0"
#features = ["mysql", "r2d2"]
