[package]
name = "rust_i_telex_teilnehmerserver"
version = "0.1.0"
authors = ["soruh <mail@soruh.de>"]
edition = "2018"

[dependencies]
nom = "4.2.3"
byteorder = "1.3.2" # should be obsolete
dotenv = "0.14.1"
crossbeam = "0.7.2"
lazy_static = "1.4.0"

[dependencies.rusqlite]
version = "0.20.0"
features = []
