[package]
name = "rust_i_telex_teilnehmerserver"
version = "0.1.0"
authors = ["soruh <mail@soruh.de>"]
edition = "2018"
description = "The I-Telex Server rewritten in rust"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.25"
thiserror = "1.0.9"
# tokio = { version = "0.2.6", features = ["full"] }
async-std = { version = "1.4.0", features = ["attributes"] }
futures = "0.3.1"
ctrlc = "3.1.3"