unstable_features = true
version = "Two"
edition = "2018"

format_code_in_doc_comments = true
wrap_comments = true
max_width = 100
comment_width = 80

overflow_delimited_expr = true
reorder_impl_items = true
merge_imports = true

use_field_init_shorthand = true
condense_wildcard_suffixes = true

use_small_heuristics = "Max"

blank_lines_lower_bound = 0
blank_lines_upper_bound = 1

format_macro_matchers = true
format_macro_bodies = true

format_strings = true
# imports_layout = "Vertical"
inline_attribute_width = 80